### ISSUE TITLE
Failure to install on microk8s due to PodDisruptionBudget version

### ISSUE THREAD

**Issue by cvgaviao** [Apicurio/apicurio-registry-operator#225] opened 2023-06-18 17:35 UTC
I tried to install `apicurio-registry-operator` on my local microk8s (v.1.27.3) and got this error:
   
```
2023-06-18T17:26:58.836Z INFO controller-runtime.metrics metrics server is starting to listen {"addr": ":8080"}
2023-06-18T17:26:58.941Z INFO controller-runtime.injectors-warning Injectors are deprecated, and will be removed in v0.10.x
2023-06-18T17:26:58.941Z INFO controller-runtime.injectors-warning Injectors are deprecated, and will be removed in v0.10.x
2023-06-18T17:26:58.941Z INFO controller-runtime.injectors-warning Injectors are deprecated, and will be removed in v0.10.x
2023-06-18T17:26:58.941Z INFO controller-runtime.injectors-warning Injectors are deprecated, and will be removed in v0.10.x
2023-06-18T17:26:58.941Z INFO controller-runtime.injectors-warning Injectors are deprecated, and will be removed in v0.10.x
2023-06-18T17:26:58.941Z INFO controller-runtime.injectors-warning Injectors are deprecated, and will be removed in v0.10.x
2023-06-18T17:26:58.941Z INFO controller-runtime.injectors-warning Injectors are deprecated, and will be removed in v0.10.x
2023-06-18T17:26:58.941Z INFO controller-runtime.injectors-warning Injectors are deprecated, and will be removed in v0.10.x
2023-06-18T17:26:58.941Z INFO controller-runtime.injectors-warning Injectors are deprecated, and will be removed in v0.10.x
2023-06-18T17:26:58.941Z INFO controller-runtime.injectors-warning Injectors are deprecated, and will be removed in v0.10.x
2023-06-18T17:26:58.941Z INFO controller-runtime.injectors-warning Injectors are deprecated, and will be removed in v0.10.x
2023-06-18T17:26:58.941Z INFO controller-runtime.injectors-warning Injectors are deprecated, and will be removed in v0.10.x
2023-06-18T17:26:58.941Z INFO controller-runtime.injectors-warning Injectors are deprecated, and will be removed in v0.10.x
2023-06-18T17:26:58.941Z INFO controller-runtime.injectors-warning Injectors are deprecated, and will be removed in v0.10.x
2023-06-18T17:26:58.941Z INFO controller-runtime.injectors-warning Injectors are deprecated, and will be removed in v0.10.x
2023-06-18T17:26:58.941Z INFO controller-runtime.injectors-warning Injectors are deprecated, and will be removed in v0.10.x
2023-06-18T17:26:58.941Z INFO controller-runtime.injectors-warning Injectors are deprecated, and will be removed in v0.10.x
2023-06-18T17:26:58.941Z INFO setup starting manager
I0618 17:26:58.942058       1 leaderelection.go:243] attempting to acquire leader lease apicurio-registry-operator-namespace/0eef189c.apicur.io...
2023-06-18T17:26:58.942Z INFO controller-runtime.manager starting metrics server {"path": "/metrics"}
I0618 17:27:16.451111       1 leaderelection.go:253] successfully acquired lease apicurio-registry-operator-namespace/0eef189c.apicur.io
2023-06-18T17:27:16.452Z DEBUG controller-runtime.manager.events Normal {"object": {"kind":"ConfigMap","namespace":"apicurio-registry-operator-namespace","name":"0eef189c.apicur.io","uid":"39bdb628-3d62-4e0f-a792-0dc6f77094a6","apiVersion":"v1","resourceVersion":"24256"}, "reason": "LeaderElection", "message": "apicurio-registry-operator-77d684558d-5j5rr_e9a6e7f7-e735-4950-a2ef-eef3f66c1058 became leader"}
2023-06-18T17:27:16.452Z DEBUG controller-runtime.manager.events Normal {"object": {"kind":"Lease","namespace":"apicurio-registry-operator-namespace","name":"0eef189c.apicur.io","uid":"b0a4e663-6fb0-4eaf-a91d-0f7321e7e938","apiVersion":"coordination.k8s.io/v1","resourceVersion":"24257"}, "reason": "LeaderElection", "message": "apicurio-registry-operator-77d684558d-5j5rr_e9a6e7f7-e735-4950-a2ef-eef3f66c1058 became leader"}
2023-06-18T17:27:16.452Z INFO controller-runtime.manager.controller.ApicurioRegistry-controller Starting EventSource {"reconciler group": "registry.apicur.io", "reconciler kind": "ApicurioRegistry", "source": "kind source: /, Kind="}
2023-06-18T17:27:16.628Z INFO controller-runtime.manager.controller.ApicurioRegistry-controller Starting EventSource {"reconciler group": "registry.apicur.io", "reconciler kind": "ApicurioRegistry", "source": "kind source: /, Kind="}
2023-06-18T17:27:16.729Z INFO controller-runtime.manager.controller.ApicurioRegistry-controller Starting EventSource {"reconciler group": "registry.apicur.io", "reconciler kind": "ApicurioRegistry", "source": "kind source: /, Kind="}
2023-06-18T17:27:16.829Z INFO controller-runtime.manager.controller.ApicurioRegistry-controller Starting EventSource {"reconciler group": "registry.apicur.io", "reconciler kind": "ApicurioRegistry", "source": "kind source: /, Kind="}
2023-06-18T17:27:16.930Z INFO controller-runtime.manager.controller.ApicurioRegistry-controller Starting EventSource {"reconciler group": "registry.apicur.io", "reconciler kind": "ApicurioRegistry", "source": "kind source: /, Kind="}
2023-06-18T17:27:16.939Z ERROR controller-runtime.source if kind is a CRD, it should be installed before calling Start {"kind": "PodDisruptionBudget.policy", "error": "no matches for kind \"PodDisruptionBudget\" in version \"policy/v1beta1\""}
github.com/go-logr/zapr.(*zapLogger).Error
 /go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start
 /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/source/source.go:117
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
 /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:168
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
 /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/internal/controller/controller.go:218
sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1
 /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.0/pkg/manager/internal.go:659
2023-06-18T17:27:16.940Z ERROR setup problem running manager {"error": "no matches for kind \"PodDisruptionBudget\" in version \"policy/v1beta1\""}
github.com/go-logr/zapr.(*zapLogger).Error
 /go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
main.main
 /workspace/main.go:128
runtime.main
 /usr/local/go/src/runtime/proc.go:203
```

**Comment by maver1ck** [comment] 2023-06-23 10:33
It's duplicate of https://github.com/Apicurio/apicurio-registry-operator/issues/199

**Comment by jsenko** [comment] 2023-10-10 11:59
Done https://github.com/Apicurio/apicurio-registry-operator/releases/tag/v1.1.0-v2.4.12.final

**Closed by jsenko** 2023-10-10 11:59 UTC
